package com.cmit.hlwjs.datatoexcel.mapper;

import com.cmit.hlwjs.datatoexcel.model.RptDataMmAp;
import java.util.List;

public interface RptDataMmApMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPT_DATA_MM_AP
     *
     * @mbg.generated
     */
    int insert(RptDataMmAp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPT_DATA_MM_AP
     *
     * @mbg.generated
     */
    List<RptDataMmAp> selectAll();
}