package com.cmit.exceltosql.mapper;

import com.cmit.exceltosql.model.RptDataBcMmAp;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface RptDataBcMmApMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rpt_data_bc_mm_ap
     *
     * @mbggenerated
     */
    int insert(RptDataBcMmAp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rpt_data_bc_mm_ap
     *
     * @mbggenerated
     */
    List<RptDataBcMmAp> selectAll();
}