package com.cmit.exceltosql.model;

import java.math.BigDecimal;

public class RptDataBcMmAp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.AP_CODE
     *
     * @mbggenerated
     */
    private String apCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.MP_CODE
     *
     * @mbggenerated
     */
    private String mpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.AP_NAME
     *
     * @mbggenerated
     */
    private String apName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BC_REASON
     *
     * @mbggenerated
     */
    private String bcReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.LI_CLAUSE
     *
     * @mbggenerated
     */
    private String liClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.PRO_SCHEME
     *
     * @mbggenerated
     */
    private String proScheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.CRE_DEDUCTION
     *
     * @mbggenerated
     */
    private String creDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BC_APID
     *
     * @mbggenerated
     */
    private String bcApid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BC_APNAME
     *
     * @mbggenerated
     */
    private String bcApname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BUSI_TYPE
     *
     * @mbggenerated
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.START_TYRE
     *
     * @mbggenerated
     */
    private String startTyre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BC_MONTH
     *
     * @mbggenerated
     */
    private String bcMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BUSI_CODE
     *
     * @mbggenerated
     */
    private String busiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rpt_data_bc_mm_ap.BUSI_NAME
     *
     * @mbggenerated
     */
    private String busiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.AP_CODE
     *
     * @return the value of rpt_data_bc_mm_ap.AP_CODE
     *
     * @mbggenerated
     */
    public String getApCode() {
        return apCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.AP_CODE
     *
     * @param apCode the value for rpt_data_bc_mm_ap.AP_CODE
     *
     * @mbggenerated
     */
    public void setApCode(String apCode) {
        this.apCode = apCode == null ? null : apCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.MP_CODE
     *
     * @return the value of rpt_data_bc_mm_ap.MP_CODE
     *
     * @mbggenerated
     */
    public String getMpCode() {
        return mpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.MP_CODE
     *
     * @param mpCode the value for rpt_data_bc_mm_ap.MP_CODE
     *
     * @mbggenerated
     */
    public void setMpCode(String mpCode) {
        this.mpCode = mpCode == null ? null : mpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.AP_NAME
     *
     * @return the value of rpt_data_bc_mm_ap.AP_NAME
     *
     * @mbggenerated
     */
    public String getApName() {
        return apName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.AP_NAME
     *
     * @param apName the value for rpt_data_bc_mm_ap.AP_NAME
     *
     * @mbggenerated
     */
    public void setApName(String apName) {
        this.apName = apName == null ? null : apName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BC_REASON
     *
     * @return the value of rpt_data_bc_mm_ap.BC_REASON
     *
     * @mbggenerated
     */
    public String getBcReason() {
        return bcReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BC_REASON
     *
     * @param bcReason the value for rpt_data_bc_mm_ap.BC_REASON
     *
     * @mbggenerated
     */
    public void setBcReason(String bcReason) {
        this.bcReason = bcReason == null ? null : bcReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.LI_CLAUSE
     *
     * @return the value of rpt_data_bc_mm_ap.LI_CLAUSE
     *
     * @mbggenerated
     */
    public String getLiClause() {
        return liClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.LI_CLAUSE
     *
     * @param liClause the value for rpt_data_bc_mm_ap.LI_CLAUSE
     *
     * @mbggenerated
     */
    public void setLiClause(String liClause) {
        this.liClause = liClause == null ? null : liClause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.PRO_SCHEME
     *
     * @return the value of rpt_data_bc_mm_ap.PRO_SCHEME
     *
     * @mbggenerated
     */
    public String getProScheme() {
        return proScheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.PRO_SCHEME
     *
     * @param proScheme the value for rpt_data_bc_mm_ap.PRO_SCHEME
     *
     * @mbggenerated
     */
    public void setProScheme(String proScheme) {
        this.proScheme = proScheme == null ? null : proScheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.CRE_DEDUCTION
     *
     * @return the value of rpt_data_bc_mm_ap.CRE_DEDUCTION
     *
     * @mbggenerated
     */
    public String getCreDeduction() {
        return creDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.CRE_DEDUCTION
     *
     * @param creDeduction the value for rpt_data_bc_mm_ap.CRE_DEDUCTION
     *
     * @mbggenerated
     */
    public void setCreDeduction(String creDeduction) {
        this.creDeduction = creDeduction == null ? null : creDeduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BC_APID
     *
     * @return the value of rpt_data_bc_mm_ap.BC_APID
     *
     * @mbggenerated
     */
    public String getBcApid() {
        return bcApid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BC_APID
     *
     * @param bcApid the value for rpt_data_bc_mm_ap.BC_APID
     *
     * @mbggenerated
     */
    public void setBcApid(String bcApid) {
        this.bcApid = bcApid == null ? null : bcApid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BC_APNAME
     *
     * @return the value of rpt_data_bc_mm_ap.BC_APNAME
     *
     * @mbggenerated
     */
    public String getBcApname() {
        return bcApname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BC_APNAME
     *
     * @param bcApname the value for rpt_data_bc_mm_ap.BC_APNAME
     *
     * @mbggenerated
     */
    public void setBcApname(String bcApname) {
        this.bcApname = bcApname == null ? null : bcApname.trim();;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BUSI_TYPE
     *
     * @return the value of rpt_data_bc_mm_ap.BUSI_TYPE
     *
     * @mbggenerated
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BUSI_TYPE
     *
     * @param busiType the value for rpt_data_bc_mm_ap.BUSI_TYPE
     *
     * @mbggenerated
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.START_TYRE
     *
     * @return the value of rpt_data_bc_mm_ap.START_TYRE
     *
     * @mbggenerated
     */
    public String getStartTyre() {
        return startTyre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.START_TYRE
     *
     * @param startTyre the value for rpt_data_bc_mm_ap.START_TYRE
     *
     * @mbggenerated
     */
    public void setStartTyre(String startTyre) {
        this.startTyre = startTyre == null ? null : startTyre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BC_MONTH
     *
     * @return the value of rpt_data_bc_mm_ap.BC_MONTH
     *
     * @mbggenerated
     */
    public String getBcMonth() {
        return bcMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BC_MONTH
     *
     * @param bcMonth the value for rpt_data_bc_mm_ap.BC_MONTH
     *
     * @mbggenerated
     */
    public void setBcMonth(String bcMonth) {
        this.bcMonth = bcMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BUSI_CODE
     *
     * @return the value of rpt_data_bc_mm_ap.BUSI_CODE
     *
     * @mbggenerated
     */
    public String getBusiCode() {
        return busiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BUSI_CODE
     *
     * @param busiCode the value for rpt_data_bc_mm_ap.BUSI_CODE
     *
     * @mbggenerated
     */
    public void setBusiCode(String busiCode) {
        this.busiCode = busiCode == null ? null : busiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rpt_data_bc_mm_ap.BUSI_NAME
     *
     * @return the value of rpt_data_bc_mm_ap.BUSI_NAME
     *
     * @mbggenerated
     */
    public String getBusiName() {
        return busiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rpt_data_bc_mm_ap.BUSI_NAME
     *
     * @param busiName the value for rpt_data_bc_mm_ap.BUSI_NAME
     *
     * @mbggenerated
     */
    public void setBusiName(String busiName) {
        this.busiName = busiName == null ? null : busiName.trim();
    }
}