package com.cmit.hlwjs.datatoexcel.model;

import java.math.BigDecimal;
import java.util.Date;

public class RptDataMmAp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.BILL_MONTH
     *
     * @mbg.generated
     */
    private Date billMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.AP_CODE_U
     *
     * @mbg.generated
     */
    private String apCodeU;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.AP_CODE
     *
     * @mbg.generated
     */
    private String apCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.AP_NAME
     *
     * @mbg.generated
     */
    private String apName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.RATIO_TAX_OUT
     *
     * @mbg.generated
     */
    private BigDecimal ratioTaxOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal feeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_VGOP
     *
     * @mbg.generated
     */
    private BigDecimal feeVgop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_CUT_SUB
     *
     * @mbg.generated
     */
    private BigDecimal feeCutSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_ABSENCE
     *
     * @mbg.generated
     */
    private BigDecimal feeAbsence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_CUT
     *
     * @mbg.generated
     */
    private BigDecimal feeCut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_PRESENT
     *
     * @mbg.generated
     */
    private BigDecimal feePresent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_TAX_OUT
     *
     * @mbg.generated
     */
    private BigDecimal feeTaxOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_ALLOT_SELF
     *
     * @mbg.generated
     */
    private BigDecimal feeAllotSelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_ALLOT_OTHER
     *
     * @mbg.generated
     */
    private BigDecimal feeAllotOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_ALLOT_CH
     *
     * @mbg.generated
     */
    private BigDecimal feeAllotCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_ALLOT_AP
     *
     * @mbg.generated
     */
    private BigDecimal feeAllotAp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_INCOME_CH
     *
     * @mbg.generated
     */
    private BigDecimal feeIncomeCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_INVOICE_AP
     *
     * @mbg.generated
     */
    private BigDecimal feeInvoiceAp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.FEE_INVOICE_SELF
     *
     * @mbg.generated
     */
    private BigDecimal feeInvoiceSelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.DATA_TYPE
     *
     * @mbg.generated
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RPT_DATA_MM_AP.DATA_RANGE
     *
     * @mbg.generated
     */
    private String dataRange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.BILL_MONTH
     *
     * @return the value of RPT_DATA_MM_AP.BILL_MONTH
     *
     * @mbg.generated
     */
    public Date getBillMonth() {
        return billMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.BILL_MONTH
     *
     * @param billMonth the value for RPT_DATA_MM_AP.BILL_MONTH
     *
     * @mbg.generated
     */
    public void setBillMonth(Date billMonth) {
        this.billMonth = billMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.AP_CODE_U
     *
     * @return the value of RPT_DATA_MM_AP.AP_CODE_U
     *
     * @mbg.generated
     */
    public String getApCodeU() {
        return apCodeU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.AP_CODE_U
     *
     * @param apCodeU the value for RPT_DATA_MM_AP.AP_CODE_U
     *
     * @mbg.generated
     */
    public void setApCodeU(String apCodeU) {
        this.apCodeU = apCodeU == null ? null : apCodeU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.AP_CODE
     *
     * @return the value of RPT_DATA_MM_AP.AP_CODE
     *
     * @mbg.generated
     */
    public String getApCode() {
        return apCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.AP_CODE
     *
     * @param apCode the value for RPT_DATA_MM_AP.AP_CODE
     *
     * @mbg.generated
     */
    public void setApCode(String apCode) {
        this.apCode = apCode == null ? null : apCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.AP_NAME
     *
     * @return the value of RPT_DATA_MM_AP.AP_NAME
     *
     * @mbg.generated
     */
    public String getApName() {
        return apName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.AP_NAME
     *
     * @param apName the value for RPT_DATA_MM_AP.AP_NAME
     *
     * @mbg.generated
     */
    public void setApName(String apName) {
        this.apName = apName == null ? null : apName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.RATIO_TAX_OUT
     *
     * @return the value of RPT_DATA_MM_AP.RATIO_TAX_OUT
     *
     * @mbg.generated
     */
    public BigDecimal getRatioTaxOut() {
        return ratioTaxOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.RATIO_TAX_OUT
     *
     * @param ratioTaxOut the value for RPT_DATA_MM_AP.RATIO_TAX_OUT
     *
     * @mbg.generated
     */
    public void setRatioTaxOut(BigDecimal ratioTaxOut) {
        this.ratioTaxOut = ratioTaxOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_TOTAL
     *
     * @return the value of RPT_DATA_MM_AP.FEE_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getFeeTotal() {
        return feeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_TOTAL
     *
     * @param feeTotal the value for RPT_DATA_MM_AP.FEE_TOTAL
     *
     * @mbg.generated
     */
    public void setFeeTotal(BigDecimal feeTotal) {
        this.feeTotal = feeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_VGOP
     *
     * @return the value of RPT_DATA_MM_AP.FEE_VGOP
     *
     * @mbg.generated
     */
    public BigDecimal getFeeVgop() {
        return feeVgop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_VGOP
     *
     * @param feeVgop the value for RPT_DATA_MM_AP.FEE_VGOP
     *
     * @mbg.generated
     */
    public void setFeeVgop(BigDecimal feeVgop) {
        this.feeVgop = feeVgop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_CUT_SUB
     *
     * @return the value of RPT_DATA_MM_AP.FEE_CUT_SUB
     *
     * @mbg.generated
     */
    public BigDecimal getFeeCutSub() {
        return feeCutSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_CUT_SUB
     *
     * @param feeCutSub the value for RPT_DATA_MM_AP.FEE_CUT_SUB
     *
     * @mbg.generated
     */
    public void setFeeCutSub(BigDecimal feeCutSub) {
        this.feeCutSub = feeCutSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_ABSENCE
     *
     * @return the value of RPT_DATA_MM_AP.FEE_ABSENCE
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAbsence() {
        return feeAbsence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_ABSENCE
     *
     * @param feeAbsence the value for RPT_DATA_MM_AP.FEE_ABSENCE
     *
     * @mbg.generated
     */
    public void setFeeAbsence(BigDecimal feeAbsence) {
        this.feeAbsence = feeAbsence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_CUT
     *
     * @return the value of RPT_DATA_MM_AP.FEE_CUT
     *
     * @mbg.generated
     */
    public BigDecimal getFeeCut() {
        return feeCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_CUT
     *
     * @param feeCut the value for RPT_DATA_MM_AP.FEE_CUT
     *
     * @mbg.generated
     */
    public void setFeeCut(BigDecimal feeCut) {
        this.feeCut = feeCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_PRESENT
     *
     * @return the value of RPT_DATA_MM_AP.FEE_PRESENT
     *
     * @mbg.generated
     */
    public BigDecimal getFeePresent() {
        return feePresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_PRESENT
     *
     * @param feePresent the value for RPT_DATA_MM_AP.FEE_PRESENT
     *
     * @mbg.generated
     */
    public void setFeePresent(BigDecimal feePresent) {
        this.feePresent = feePresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_TAX_OUT
     *
     * @return the value of RPT_DATA_MM_AP.FEE_TAX_OUT
     *
     * @mbg.generated
     */
    public BigDecimal getFeeTaxOut() {
        return feeTaxOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_TAX_OUT
     *
     * @param feeTaxOut the value for RPT_DATA_MM_AP.FEE_TAX_OUT
     *
     * @mbg.generated
     */
    public void setFeeTaxOut(BigDecimal feeTaxOut) {
        this.feeTaxOut = feeTaxOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_SELF
     *
     * @return the value of RPT_DATA_MM_AP.FEE_ALLOT_SELF
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAllotSelf() {
        return feeAllotSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_SELF
     *
     * @param feeAllotSelf the value for RPT_DATA_MM_AP.FEE_ALLOT_SELF
     *
     * @mbg.generated
     */
    public void setFeeAllotSelf(BigDecimal feeAllotSelf) {
        this.feeAllotSelf = feeAllotSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_OTHER
     *
     * @return the value of RPT_DATA_MM_AP.FEE_ALLOT_OTHER
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAllotOther() {
        return feeAllotOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_OTHER
     *
     * @param feeAllotOther the value for RPT_DATA_MM_AP.FEE_ALLOT_OTHER
     *
     * @mbg.generated
     */
    public void setFeeAllotOther(BigDecimal feeAllotOther) {
        this.feeAllotOther = feeAllotOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_CH
     *
     * @return the value of RPT_DATA_MM_AP.FEE_ALLOT_CH
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAllotCh() {
        return feeAllotCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_CH
     *
     * @param feeAllotCh the value for RPT_DATA_MM_AP.FEE_ALLOT_CH
     *
     * @mbg.generated
     */
    public void setFeeAllotCh(BigDecimal feeAllotCh) {
        this.feeAllotCh = feeAllotCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_AP
     *
     * @return the value of RPT_DATA_MM_AP.FEE_ALLOT_AP
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAllotAp() {
        return feeAllotAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_ALLOT_AP
     *
     * @param feeAllotAp the value for RPT_DATA_MM_AP.FEE_ALLOT_AP
     *
     * @mbg.generated
     */
    public void setFeeAllotAp(BigDecimal feeAllotAp) {
        this.feeAllotAp = feeAllotAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_INCOME_CH
     *
     * @return the value of RPT_DATA_MM_AP.FEE_INCOME_CH
     *
     * @mbg.generated
     */
    public BigDecimal getFeeIncomeCh() {
        return feeIncomeCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_INCOME_CH
     *
     * @param feeIncomeCh the value for RPT_DATA_MM_AP.FEE_INCOME_CH
     *
     * @mbg.generated
     */
    public void setFeeIncomeCh(BigDecimal feeIncomeCh) {
        this.feeIncomeCh = feeIncomeCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_INVOICE_AP
     *
     * @return the value of RPT_DATA_MM_AP.FEE_INVOICE_AP
     *
     * @mbg.generated
     */
    public BigDecimal getFeeInvoiceAp() {
        return feeInvoiceAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_INVOICE_AP
     *
     * @param feeInvoiceAp the value for RPT_DATA_MM_AP.FEE_INVOICE_AP
     *
     * @mbg.generated
     */
    public void setFeeInvoiceAp(BigDecimal feeInvoiceAp) {
        this.feeInvoiceAp = feeInvoiceAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.FEE_INVOICE_SELF
     *
     * @return the value of RPT_DATA_MM_AP.FEE_INVOICE_SELF
     *
     * @mbg.generated
     */
    public BigDecimal getFeeInvoiceSelf() {
        return feeInvoiceSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.FEE_INVOICE_SELF
     *
     * @param feeInvoiceSelf the value for RPT_DATA_MM_AP.FEE_INVOICE_SELF
     *
     * @mbg.generated
     */
    public void setFeeInvoiceSelf(BigDecimal feeInvoiceSelf) {
        this.feeInvoiceSelf = feeInvoiceSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.DATA_TYPE
     *
     * @return the value of RPT_DATA_MM_AP.DATA_TYPE
     *
     * @mbg.generated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.DATA_TYPE
     *
     * @param dataType the value for RPT_DATA_MM_AP.DATA_TYPE
     *
     * @mbg.generated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RPT_DATA_MM_AP.DATA_RANGE
     *
     * @return the value of RPT_DATA_MM_AP.DATA_RANGE
     *
     * @mbg.generated
     */
    public String getDataRange() {
        return dataRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RPT_DATA_MM_AP.DATA_RANGE
     *
     * @param dataRange the value for RPT_DATA_MM_AP.DATA_RANGE
     *
     * @mbg.generated
     */
    public void setDataRange(String dataRange) {
        this.dataRange = dataRange == null ? null : dataRange.trim();
    }
}